dateModified: 1583938200
email:
  fromEmail: itstuartsmith@gmail.com
  fromName: craft-playground
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  aa262672-4fef-4032-a8a3-4ddee152e9ff:
    name: Common
fields:
  278fae23-10c9-483e-bbbd-66b51d910de1:
    contentColumnType: string
    fieldGroup: aa262672-4fef-4032-a8a3-4ddee152e9ff
    handle: accordionField
    instructions: ''
    name: 'Accordion Field'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_accordionfield}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  bc502cc0-05c7-4e7f-969f-0241f84d6fe8:
    contentColumnType: text
    fieldGroup: aa262672-4fef-4032-a8a3-4ddee152e9ff
    handle: heroText
    instructions: ''
    name: 'Hero text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
matrixBlockTypes:
  c2e81262-d385-49cd-b5ad-83909a47fc16:
    field: 278fae23-10c9-483e-bbbd-66b51d910de1
    fieldLayouts:
      ad1b65d7-1fb8-433c-9ea5-539bfa3102fb:
        tabs:
          -
            fields:
              28df69ef-303e-4f25-a8ef-5799fac7211c:
                required: false
                sortOrder: 2
              67f7373f-7973-45a1-90bd-5afa856434a8:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      28df69ef-303e-4f25-a8ef-5799fac7211c:
        contentColumnType: string(7)
        fieldGroup: null
        handle: accordionDescription
        instructions: ''
        name: 'Accordion description'
        searchable: true
        settings:
          defaultColor: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\Color
      67f7373f-7973-45a1-90bd-5afa856434a8:
        contentColumnType: text
        fieldGroup: null
        handle: accordionText
        instructions: ''
        name: 'accordion text'
        searchable: true
        settings:
          byteLimit: null
          charLimit: null
          code: ''
          columnType: null
          initialRows: '4'
          multiline: ''
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
    handle: accordiontext
    name: accordionText
    sortOrder: 1
plugins:
  craftplugin:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  instant-analytics:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  kint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      kintDisplayTheme: solarized.css
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
sections:
  9d03cd59-15a3-40bf-84d1-85e4ed831bca:
    enableVersioning: true
    entryTypes:
      0d495f0f-1d50-4302-bc4d-47e5e755dc16:
        fieldLayouts:
          40a48357-7339-4048-8bc4-5156ce26a3f5:
            tabs:
              -
                fields:
                  bc502cc0-05c7-4e7f-969f-0241f84d6fe8:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: firstSection
        hasTitleField: true
        name: 'First section'
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: firstSection
    name: 'First section'
    propagationMethod: all
    siteSettings:
      94949589-62c7-4508-b8fb-19a48dff4c9b:
        enabledByDefault: true
        hasUrls: true
        template: first-section
        uriFormat: 'first-section{slug}'
    type: channel
  d810bf93-6768-41a9-bba3-936fa231f9b9:
    enableVersioning: true
    entryTypes:
      be8340a6-3e58-49e0-b7d3-1fe196045c8b:
        fieldLayouts:
          734e4f07-21e1-4872-9f81-b48746f367a1:
            tabs:
              -
                fields:
                  278fae23-10c9-483e-bbbd-66b51d910de1:
                    required: false
                    sortOrder: 1
                  bc502cc0-05c7-4e7f-969f-0241f84d6fe8:
                    required: false
                    sortOrder: 2
                name: 'Tab 1'
                sortOrder: 1
        handle: secondSection
        hasTitleField: true
        name: 'second section'
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: secondSection
    name: 'Second section'
    propagationMethod: all
    siteSettings:
      94949589-62c7-4508-b8fb-19a48dff4c9b:
        enabledByDefault: true
        hasUrls: true
        template: first-section
        uriFormat: 'second-section/{slug}'
    type: channel
siteGroups:
  ab544d6d-36ec-4b7c-94de-b06c3e3db8e7:
    name: craft-playground
sites:
  94949589-62c7-4508-b8fb-19a48dff4c9b:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: craft-playground
    primary: true
    siteGroup: ab544d6d-36ec-4b7c-94de-b06c3e3db8e7
    sortOrder: 1
system:
  edition: solo
  live: true
  name: craft-playground
  schemaVersion: 3.4.10
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
